/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as AuthenticatedTagihanRouteImport } from './routes/_authenticated/tagihan'
import { Route as AuthenticatedNotaRouteImport } from './routes/_authenticated/nota'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicMidtransNotificationRouteImport } from './routes/api/public/midtrans-notification'
import { Route as AuthenticatedTagihanIdRouteImport } from './routes/_authenticated/tagihan.$id'
import { Route as AuthenticatedNotaIdRouteImport } from './routes/_authenticated/nota.$id'
import { Route as AuthenticatedAdminTahunAjaranRouteImport } from './routes/_authenticated/admin.tahun-ajaran'
import { Route as AuthenticatedAdminSiswaRouteImport } from './routes/_authenticated/admin.siswa'
import { Route as AuthenticatedAdminOrangTuaRouteImport } from './routes/_authenticated/admin.orang-tua'
import { Route as AuthenticatedAdminKelasRouteImport } from './routes/_authenticated/admin.kelas'
import { Route as AuthenticatedAdminJenisTagihanRouteImport } from './routes/_authenticated/admin.jenis-tagihan'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTagihanRoute = AuthenticatedTagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotaRoute = AuthenticatedNotaRouteImport.update({
  id: '/nota',
  path: '/nota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMidtransNotificationRoute =
  ApiPublicMidtransNotificationRouteImport.update({
    id: '/api/public/midtrans-notification',
    path: '/api/public/midtrans-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTagihanIdRoute = AuthenticatedTagihanIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTagihanRoute,
} as any)
const AuthenticatedNotaIdRoute = AuthenticatedNotaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedNotaRoute,
} as any)
const AuthenticatedAdminTahunAjaranRoute =
  AuthenticatedAdminTahunAjaranRouteImport.update({
    id: '/admin/tahun-ajaran',
    path: '/admin/tahun-ajaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSiswaRoute = AuthenticatedAdminSiswaRouteImport.update({
  id: '/admin/siswa',
  path: '/admin/siswa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOrangTuaRoute =
  AuthenticatedAdminOrangTuaRouteImport.update({
    id: '/admin/orang-tua',
    path: '/admin/orang-tua',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKelasRoute = AuthenticatedAdminKelasRouteImport.update({
  id: '/admin/kelas',
  path: '/admin/kelas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminJenisTagihanRoute =
  AuthenticatedAdminJenisTagihanRouteImport.update({
    id: '/admin/jenis-tagihan',
    path: '/admin/jenis-tagihan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nota': typeof AuthenticatedNotaRouteWithChildren
  '/tagihan': typeof AuthenticatedTagihanRouteWithChildren
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/jenis-tagihan': typeof AuthenticatedAdminJenisTagihanRoute
  '/admin/kelas': typeof AuthenticatedAdminKelasRoute
  '/admin/orang-tua': typeof AuthenticatedAdminOrangTuaRoute
  '/admin/siswa': typeof AuthenticatedAdminSiswaRoute
  '/admin/tahun-ajaran': typeof AuthenticatedAdminTahunAjaranRoute
  '/nota/$id': typeof AuthenticatedNotaIdRoute
  '/tagihan/$id': typeof AuthenticatedTagihanIdRoute
  '/api/public/midtrans-notification': typeof ApiPublicMidtransNotificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nota': typeof AuthenticatedNotaRouteWithChildren
  '/tagihan': typeof AuthenticatedTagihanRouteWithChildren
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/jenis-tagihan': typeof AuthenticatedAdminJenisTagihanRoute
  '/admin/kelas': typeof AuthenticatedAdminKelasRoute
  '/admin/orang-tua': typeof AuthenticatedAdminOrangTuaRoute
  '/admin/siswa': typeof AuthenticatedAdminSiswaRoute
  '/admin/tahun-ajaran': typeof AuthenticatedAdminTahunAjaranRoute
  '/nota/$id': typeof AuthenticatedNotaIdRoute
  '/tagihan/$id': typeof AuthenticatedTagihanIdRoute
  '/api/public/midtrans-notification': typeof ApiPublicMidtransNotificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/nota': typeof AuthenticatedNotaRouteWithChildren
  '/_authenticated/tagihan': typeof AuthenticatedTagihanRouteWithChildren
  '/verify/$code': typeof VerifyCodeRoute
  '/_authenticated/admin/jenis-tagihan': typeof AuthenticatedAdminJenisTagihanRoute
  '/_authenticated/admin/kelas': typeof AuthenticatedAdminKelasRoute
  '/_authenticated/admin/orang-tua': typeof AuthenticatedAdminOrangTuaRoute
  '/_authenticated/admin/siswa': typeof AuthenticatedAdminSiswaRoute
  '/_authenticated/admin/tahun-ajaran': typeof AuthenticatedAdminTahunAjaranRoute
  '/_authenticated/nota/$id': typeof AuthenticatedNotaIdRoute
  '/_authenticated/tagihan/$id': typeof AuthenticatedTagihanIdRoute
  '/api/public/midtrans-notification': typeof ApiPublicMidtransNotificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/nota'
    | '/tagihan'
    | '/verify/$code'
    | '/admin/jenis-tagihan'
    | '/admin/kelas'
    | '/admin/orang-tua'
    | '/admin/siswa'
    | '/admin/tahun-ajaran'
    | '/nota/$id'
    | '/tagihan/$id'
    | '/api/public/midtrans-notification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/nota'
    | '/tagihan'
    | '/verify/$code'
    | '/admin/jenis-tagihan'
    | '/admin/kelas'
    | '/admin/orang-tua'
    | '/admin/siswa'
    | '/admin/tahun-ajaran'
    | '/nota/$id'
    | '/tagihan/$id'
    | '/api/public/midtrans-notification'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/nota'
    | '/_authenticated/tagihan'
    | '/verify/$code'
    | '/_authenticated/admin/jenis-tagihan'
    | '/_authenticated/admin/kelas'
    | '/_authenticated/admin/orang-tua'
    | '/_authenticated/admin/siswa'
    | '/_authenticated/admin/tahun-ajaran'
    | '/_authenticated/nota/$id'
    | '/_authenticated/tagihan/$id'
    | '/api/public/midtrans-notification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  ApiPublicMidtransNotificationRoute: typeof ApiPublicMidtransNotificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tagihan': {
      id: '/_authenticated/tagihan'
      path: '/tagihan'
      fullPath: '/tagihan'
      preLoaderRoute: typeof AuthenticatedTagihanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nota': {
      id: '/_authenticated/nota'
      path: '/nota'
      fullPath: '/nota'
      preLoaderRoute: typeof AuthenticatedNotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/midtrans-notification': {
      id: '/api/public/midtrans-notification'
      path: '/api/public/midtrans-notification'
      fullPath: '/api/public/midtrans-notification'
      preLoaderRoute: typeof ApiPublicMidtransNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tagihan/$id': {
      id: '/_authenticated/tagihan/$id'
      path: '/$id'
      fullPath: '/tagihan/$id'
      preLoaderRoute: typeof AuthenticatedTagihanIdRouteImport
      parentRoute: typeof AuthenticatedTagihanRoute
    }
    '/_authenticated/nota/$id': {
      id: '/_authenticated/nota/$id'
      path: '/$id'
      fullPath: '/nota/$id'
      preLoaderRoute: typeof AuthenticatedNotaIdRouteImport
      parentRoute: typeof AuthenticatedNotaRoute
    }
    '/_authenticated/admin/tahun-ajaran': {
      id: '/_authenticated/admin/tahun-ajaran'
      path: '/admin/tahun-ajaran'
      fullPath: '/admin/tahun-ajaran'
      preLoaderRoute: typeof AuthenticatedAdminTahunAjaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/siswa': {
      id: '/_authenticated/admin/siswa'
      path: '/admin/siswa'
      fullPath: '/admin/siswa'
      preLoaderRoute: typeof AuthenticatedAdminSiswaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/orang-tua': {
      id: '/_authenticated/admin/orang-tua'
      path: '/admin/orang-tua'
      fullPath: '/admin/orang-tua'
      preLoaderRoute: typeof AuthenticatedAdminOrangTuaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/kelas': {
      id: '/_authenticated/admin/kelas'
      path: '/admin/kelas'
      fullPath: '/admin/kelas'
      preLoaderRoute: typeof AuthenticatedAdminKelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jenis-tagihan': {
      id: '/_authenticated/admin/jenis-tagihan'
      path: '/admin/jenis-tagihan'
      fullPath: '/admin/jenis-tagihan'
      preLoaderRoute: typeof AuthenticatedAdminJenisTagihanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedNotaRouteChildren {
  AuthenticatedNotaIdRoute: typeof AuthenticatedNotaIdRoute
}

const AuthenticatedNotaRouteChildren: AuthenticatedNotaRouteChildren = {
  AuthenticatedNotaIdRoute: AuthenticatedNotaIdRoute,
}

const AuthenticatedNotaRouteWithChildren =
  AuthenticatedNotaRoute._addFileChildren(AuthenticatedNotaRouteChildren)

interface AuthenticatedTagihanRouteChildren {
  AuthenticatedTagihanIdRoute: typeof AuthenticatedTagihanIdRoute
}

const AuthenticatedTagihanRouteChildren: AuthenticatedTagihanRouteChildren = {
  AuthenticatedTagihanIdRoute: AuthenticatedTagihanIdRoute,
}

const AuthenticatedTagihanRouteWithChildren =
  AuthenticatedTagihanRoute._addFileChildren(AuthenticatedTagihanRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotaRoute: typeof AuthenticatedNotaRouteWithChildren
  AuthenticatedTagihanRoute: typeof AuthenticatedTagihanRouteWithChildren
  AuthenticatedAdminJenisTagihanRoute: typeof AuthenticatedAdminJenisTagihanRoute
  AuthenticatedAdminKelasRoute: typeof AuthenticatedAdminKelasRoute
  AuthenticatedAdminOrangTuaRoute: typeof AuthenticatedAdminOrangTuaRoute
  AuthenticatedAdminSiswaRoute: typeof AuthenticatedAdminSiswaRoute
  AuthenticatedAdminTahunAjaranRoute: typeof AuthenticatedAdminTahunAjaranRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotaRoute: AuthenticatedNotaRouteWithChildren,
  AuthenticatedTagihanRoute: AuthenticatedTagihanRouteWithChildren,
  AuthenticatedAdminJenisTagihanRoute: AuthenticatedAdminJenisTagihanRoute,
  AuthenticatedAdminKelasRoute: AuthenticatedAdminKelasRoute,
  AuthenticatedAdminOrangTuaRoute: AuthenticatedAdminOrangTuaRoute,
  AuthenticatedAdminSiswaRoute: AuthenticatedAdminSiswaRoute,
  AuthenticatedAdminTahunAjaranRoute: AuthenticatedAdminTahunAjaranRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  ApiPublicMidtransNotificationRoute: ApiPublicMidtransNotificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
